# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManualInvoiceEntry.ui'
#
# Created: Mon Sep  5 21:04:06 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ManualDialog(object):
    def setupUi(self, ManualDialog):
        ManualDialog.setObjectName("ManualDialog")
        ManualDialog.resize(431, 559)
        self.verticalLayout = QtWidgets.QVBoxLayout(ManualDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(ManualDialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.InvoiceEdit = QtWidgets.QLineEdit(self.frame_3)
        self.InvoiceEdit.setObjectName("InvoiceEdit")
        self.gridLayout.addWidget(self.InvoiceEdit, 2, 2, 1, 1)
        self.TrackingBox = QtWidgets.QLineEdit(self.frame_3)
        self.TrackingBox.setObjectName("TrackingBox")
        self.gridLayout.addWidget(self.TrackingBox, 5, 2, 1, 1)
        self.CarrierBox = QtWidgets.QLineEdit(self.frame_3)
        self.CarrierBox.setObjectName("CarrierBox")
        self.gridLayout.addWidget(self.CarrierBox, 4, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.CustomerBox = QtWidgets.QComboBox(self.frame_3)
        self.CustomerBox.setObjectName("CustomerBox")
        self.gridLayout.addWidget(self.CustomerBox, 1, 2, 1, 1)
        self.DiscountSpin = QtWidgets.QSpinBox(self.frame_3)
        self.DiscountSpin.setObjectName("DiscountSpin")
        self.gridLayout.addWidget(self.DiscountSpin, 6, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.ShipDateCal = QtWidgets.QDateEdit(self.frame_3)
        self.ShipDateCal.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.ShipDateCal.setCalendarPopup(True)
        self.ShipDateCal.setObjectName("ShipDateCal")
        self.gridLayout.addWidget(self.ShipDateCal, 7, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(ManualDialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.StoreBox = QtWidgets.QComboBox(self.frame_2)
        self.StoreBox.setObjectName("StoreBox")
        self.horizontalLayout_2.addWidget(self.StoreBox)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.ItemTable = QtWidgets.QTableView(self.frame_2)
        self.ItemTable.setObjectName("ItemTable")
        self.verticalLayout_3.addWidget(self.ItemTable)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(ManualDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.GenerateLabel = QtWidgets.QLabel(self.frame)
        self.GenerateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.GenerateLabel.setObjectName("GenerateLabel")
        self.verticalLayout_2.addWidget(self.GenerateLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ASNButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ASNButton.sizePolicy().hasHeightForWidth())
        self.ASNButton.setSizePolicy(sizePolicy)
        self.ASNButton.setObjectName("ASNButton")
        self.horizontalLayout.addWidget(self.ASNButton)
        self.InvButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InvButton.sizePolicy().hasHeightForWidth())
        self.InvButton.setSizePolicy(sizePolicy)
        self.InvButton.setObjectName("InvButton")
        self.horizontalLayout.addWidget(self.InvButton)
        self.BothButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BothButton.sizePolicy().hasHeightForWidth())
        self.BothButton.setSizePolicy(sizePolicy)
        self.BothButton.setObjectName("BothButton")
        self.horizontalLayout.addWidget(self.BothButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(ManualDialog)
        QtCore.QMetaObject.connectSlotsByName(ManualDialog)

    def retranslateUi(self, ManualDialog):
        _translate = QtCore.QCoreApplication.translate
        ManualDialog.setWindowTitle(_translate("ManualDialog", "Dialog"))
        self.label_3.setText(_translate("ManualDialog", "Invoice Header"))
        self.label_4.setText(_translate("ManualDialog", "Carrier"))
        self.label_2.setText(_translate("ManualDialog", "Invoice #"))
        self.label_5.setText(_translate("ManualDialog", "Tracking #"))
        self.label_6.setText(_translate("ManualDialog", "Discount"))
        self.label_7.setText(_translate("ManualDialog", "Customer"))
        self.DiscountSpin.setSuffix(_translate("ManualDialog", "%"))
        self.label_9.setText(_translate("ManualDialog", "Ship Date"))
        self.label.setText(_translate("ManualDialog", "Items"))
        self.label_8.setText(_translate("ManualDialog", "Store"))
        self.GenerateLabel.setText(_translate("ManualDialog", "Generate Transactions"))
        self.ASNButton.setText(_translate("ManualDialog", "ASN"))
        self.InvButton.setText(_translate("ManualDialog", "Invoice"))
        self.BothButton.setText(_translate("ManualDialog", "Both"))

