# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mb_edi_pos.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 710)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.CustomerBox = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CustomerBox.sizePolicy().hasHeightForWidth())
        self.CustomerBox.setSizePolicy(sizePolicy)
        self.CustomerBox.setObjectName("CustomerBox")
        self.gridLayout.addWidget(self.CustomerBox, 0, 0, 1, 1)
        self.EditAllCheck = QtWidgets.QCheckBox(self.frame)
        self.EditAllCheck.setObjectName("EditAllCheck")
        self.gridLayout.addWidget(self.EditAllCheck, 1, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.AgeSlider = QtWidgets.QSlider(self.frame_2)
        self.AgeSlider.setMaximum(11)
        self.AgeSlider.setSliderPosition(11)
        self.AgeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.AgeSlider.setInvertedControls(False)
        self.AgeSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.AgeSlider.setObjectName("AgeSlider")
        self.horizontalLayout.addWidget(self.AgeSlider)
        self.DaysLabel = QtWidgets.QLabel(self.frame_2)
        self.DaysLabel.setObjectName("DaysLabel")
        self.horizontalLayout.addWidget(self.DaysLabel)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.FilterFrame = QtWidgets.QFrame(self.frame)
        self.FilterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FilterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FilterFrame.setObjectName("FilterFrame")
        self.FilterLayout = QtWidgets.QHBoxLayout(self.FilterFrame)
        self.FilterLayout.setObjectName("FilterLayout")
        self.gridLayout.addWidget(self.FilterFrame, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.POTable = QtWidgets.QTableView(self.centralwidget)
        self.POTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.POTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.POTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.POTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.POTable.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.POTable.setSortingEnabled(True)
        self.POTable.setObjectName("POTable")
        self.verticalLayout.addWidget(self.POTable)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 21))
        self.menubar.setObjectName("menubar")
        self.menuPurchase_Orders = QtWidgets.QMenu(self.menubar)
        self.menuPurchase_Orders.setObjectName("menuPurchase_Orders")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExecute_Shipments = QtWidgets.QAction(MainWindow)
        self.actionExecute_Shipments.setObjectName("actionExecute_Shipments")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionExport_as_Spreadsheet = QtWidgets.QAction(MainWindow)
        self.actionExport_as_Spreadsheet.setObjectName("actionExport_as_Spreadsheet")
        self.actionExport_for_Print = QtWidgets.QAction(MainWindow)
        self.actionExport_for_Print.setObjectName("actionExport_for_Print")
        self.actionView_Distro = QtWidgets.QAction(MainWindow)
        self.actionView_Distro.setObjectName("actionView_Distro")
        self.menuPurchase_Orders.addAction(self.actionExport_as_Spreadsheet)
        self.menuPurchase_Orders.addAction(self.actionExport_for_Print)
        self.menuPurchase_Orders.addAction(self.actionView_Distro)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPurchase_Orders.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EDI Integrator"))
        self.EditAllCheck.setText(_translate("MainWindow", "Edit All"))
        self.label.setText(_translate("MainWindow", "Days Old"))
        self.DaysLabel.setText(_translate("MainWindow", "360"))
        self.menuPurchase_Orders.setTitle(_translate("MainWindow", "Purchase Orders"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExecute_Shipments.setText(_translate("MainWindow", "Execute Shipments"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionExport_as_Spreadsheet.setText(_translate("MainWindow", "Export Spreadsheet"))
        self.actionExport_for_Print.setText(_translate("MainWindow", "Export for Print"))
        self.actionView_Distro.setText(_translate("MainWindow", "View Distro"))

