# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MB_EDI_Shipping.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from src.ui.viewmodels.invtable import InvoiceTable

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 626)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CustomerBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CustomerBox.sizePolicy().hasHeightForWidth())
        self.CustomerBox.setSizePolicy(sizePolicy)
        self.CustomerBox.setObjectName("CustomerBox")
        self.verticalLayout.addWidget(self.CustomerBox)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.InvoiceTable = InvoiceTable(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InvoiceTable.sizePolicy().hasHeightForWidth())
        self.InvoiceTable.setSizePolicy(sizePolicy)
        self.InvoiceTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.InvoiceTable.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.InvoiceTable.setRowCount(0)
        self.InvoiceTable.setColumnCount(4)
        self.InvoiceTable.setObjectName("InvoiceTable")
        self.InvoiceTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.InvoiceTable)
        self.EntryExecuteButton = QtWidgets.QPushButton(self.tab)
        self.EntryExecuteButton.setObjectName("EntryExecuteButton")
        self.verticalLayout_2.addWidget(self.EntryExecuteButton)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ShipDate = QtWidgets.QDateEdit(self.tab_2)
        self.ShipDate.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.ShipDate.setCalendarPopup(True)
        self.ShipDate.setObjectName("ShipDate")
        self.verticalLayout_3.addWidget(self.ShipDate)
        self.ShiplogLookupButton = QtWidgets.QPushButton(self.tab_2)
        self.ShiplogLookupButton.setObjectName("ShiplogLookupButton")
        self.verticalLayout_3.addWidget(self.ShiplogLookupButton)
        self.ShiplogLookup = QtWidgets.QTableWidget(self.tab_2)
        self.ShiplogLookup.setColumnCount(3)
        self.ShiplogLookup.setObjectName("ShiplogLookup")
        self.ShiplogLookup.setRowCount(0)
        self.ShiplogLookup.horizontalHeader().setCascadingSectionResizes(False)
        self.ShiplogLookup.horizontalHeader().setSortIndicatorShown(False)
        self.ShiplogLookup.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.ShiplogLookup)
        self.ShiplogExecuteButton = QtWidgets.QPushButton(self.tab_2)
        self.ShiplogExecuteButton.setObjectName("ShiplogExecuteButton")
        self.verticalLayout_3.addWidget(self.ShiplogExecuteButton)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 20)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        self.menuShipments = QtWidgets.QMenu(self.menubar)
        self.menuShipments.setObjectName("menuShipments")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExecute_Shipments = QtWidgets.QAction(MainWindow)
        self.actionExecute_Shipments.setObjectName("actionExecute_Shipments")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionExport_as_Spreadsheet = QtWidgets.QAction(MainWindow)
        self.actionExport_as_Spreadsheet.setObjectName("actionExport_as_Spreadsheet")
        self.actionExport_for_Print = QtWidgets.QAction(MainWindow)
        self.actionExport_for_Print.setObjectName("actionExport_for_Print")
        self.actionView_Distro = QtWidgets.QAction(MainWindow)
        self.actionView_Distro.setObjectName("actionView_Distro")
        self.menuShipments.addAction(self.actionExecute_Shipments)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuShipments.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EDI Integrator"))
        self.EntryExecuteButton.setText(_translate("MainWindow", "Execute"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Invoice Entry"))
        self.ShiplogLookupButton.setText(_translate("MainWindow", "Lookup"))
        self.ShiplogExecuteButton.setText(_translate("MainWindow", "Execute"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Shipping Lookup"))
        self.menuShipments.setTitle(_translate("MainWindow", "Shipments"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExecute_Shipments.setText(_translate("MainWindow", "Execute Shipments"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionExport_as_Spreadsheet.setText(_translate("MainWindow", "Export Spreadsheet"))
        self.actionExport_for_Print.setText(_translate("MainWindow", "Export for Print"))
        self.actionView_Distro.setText(_translate("MainWindow", "View Distro"))

